03fplaest-main/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.shortcuts import render
from core import views

app_name = "core"

urlpatterns = [
        path('', views.Index.as_view(), name="index"),

        path('accesorio/', views.accesorios.as_view(), name="accesorios"),
        path('recargas/', views.recargas.as_view(), name="recargas"),
        path('planes/', views.planes.as_view(), name="planes"),
        path('producto/', views.Producto.as_view(), name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/home/urls.py
from django.urls import path, include
from django.contrib import admin
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    
    path('categoria/', views.Categoria.as_view(), name="categoria"),
    path('nueva/categoria/', views.NewCategory.as_view(), name="newcategory"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
    
    path('accesorio/', views.accesorios.as_view(), name="accesorios"),
    path('new/accesorio/', views.NewAccesorios.as_view(), name="newaccesorios"),
    path('update/accesorio/<int:pk>/', views.UpdateAccesorios.as_view(), name="update_accesorios"),
    path('detail/accesorio/<int:pk>/', views.DetailAccesorios.as_view(), name="detail_accesorios"),
    path('delete/accesorio/<int:pk>/', views.DeleteAccesorios.as_view(), name="delete_accesorios"),
    
    path('recargas/', views.recargas.as_view(), name="recargas"),
    path('new/recargas/', views.NewRecargas.as_view(), name="newrecargas"),
    path('update/recargas/<int:pk>/', views.UpdateRecargas.as_view(), name="update_recargas"),
    path('detail/recargas/<int:pk>/', views.DetailRecargas.as_view(), name="detail_recargas"),
    path('delete/recargas/<int:pk>/', views.DeleteRecargas.as_view(), name="delete_recargas"),
    
    path('planes/', views.planes.as_view(), name="planes"),
    path('new/planes/', views.NewPlanes.as_view(), name="newplanes"),
    path('update/planes/<int:pk>/', views.UpdatePlanes.as_view(), name="update_planes"),
    path('detail/planes/<int:pk>/', views.DetailPlanes.as_view(), name="detail_planes"),
    path('delete/planes/<int:pk>/', views.DeletePlanes.as_view(), name="delete_planes"),
    
    path('producto/', views.Producto.as_view(), name="product"),
    path('nueva/producto/', views.NewProducto.as_view(), name="newproduct"),
    path('update/producto/<int:pk>/', views.UpdateProducto.as_view(), name="update_producto"),
    path('detail/producto/<int:pk>/', views.DetailProducto.as_view(), name="detail_producto"),
    path('delete/producto/<int:pk>/', views.DeleteProducto.as_view(), name="delete_producto"),
    
]

03fplaest-main/sesion/urls.py
from django.urls import path, include
from django.contrib import admin
from sesion import views

app_name = "sesion"

urlpatterns = [

    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),

]

03fplaest-main/sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('administrador/', include("home.urls")),
    path('sesion/', include("sesion.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/core/models.py
from django.db import models

# Create your models here.

03fplaest-main/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.conf import settings
from home.models import *
# Create your views here.


class Index(generic.View):
    template_name = "core/celmex2.html"
    context = {}

    def get(self, request):
        self.context = {
            "products": Product.objects.all()
        }
        return render(request, self.template_name, self.context)


class Producto(generic.View):
    template_name = "home/product/product.html"
    context = {}
    def get(self, request):
        #Armasgay es la variable donde se guarda la consulta de base de datos
        self.context = {
            "Armasgay": Product.objects.all()
        }
        return render(request, self.template_name, self.context)

class accesorios(generic.View):
    template_name = "core/UsuarioAccesorios.html"
    context = {}

    def get(self, request):
        self.context = {
            "accesorios": Accesorios.objects.all()
        }
        return render(request, self.template_name, self.context)

class recargas(generic.View):
    template_name = "core/UsuarioRecargas.html"
    context = {}

    def get(self, request):
        self.context = {
            "recargas": Recargas.objects.all()
        }
        return render(request, self.template_name, self.context)

class planes(generic.View):
    template_name = "core/UsuarioPlanes.html"
    context = {}

    def get(self, request):
        self.context = {
            "planes": Planes.objects.all()
        }
        return render(request, self.template_name, self.context)

03fplaest-main/templates/core/UsuarioAccesorios.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CelMex</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    body {
      background-color: #2f8efa;
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }

    .header {
      background-color: #0d6efd;
    }

    .hero {
      padding: 100px 0;
      text-align: center;
    }

    .hero img {
      max-width: 100%;
      height: auto;
    }

    .telefonos {
      padding: 50px 0;
      text-align: center;
    }

    .product-container {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 20px;
      border: 1px solid #0d6efd;
      border-radius: 10px;
      margin-bottom: 20px;
    }

    .product-container img {
      max-width: 100%;
      height: auto;
      border: 1px solid #0d6efd;
      border-radius: 10px;
    }

    .footer {
      background-color: #0d6efd;
      padding: 50px 0;
      color: white;
    }
  </style>
</head>

<body>


  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">
          <img src="{% static 'images/logo2-removebg-preview(1).png' %}" alt="Tu Sitio Web" width="100px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'core:index' %}">Productos</a>
            <a class="nav-link active" href="{% url 'core:accesorios' %}">Accesorios</a>
            <a class="nav-link" href="{% url 'core:planes' %}">Planes</a>
            <a class="nav-link" href="{% url 'core:recargas' %}">Recargas</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'home:index' %}">admin</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <section class="telefonos">
    <div class="container">
      <h2 class="mb-4">Accesorios</h2>
      <div class="row">
        {% for acc in accesorios %}
        <div class="col-md-4">
          <div class="product-container">
            <img src="{{ acc.image.url }}" alt="{{ acc.accesorios_name }}"
              class="img-fluid rounded shadow-lg border border-primary">
            <h3>{{ acc.accesorios_name }}</h3>
            <h4 class="product-description">{{ acc.description }}</h4>
            <h5>${{ acc.price }}</h5>
            <a href="https://celmex.ola.click/products" class="btn btn-primary">Ver más</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>Redes sociales</h3>
          <ul class="list-unstyled">
            <li><a href="https://www.facebook.com/profile.php?id=61551257362781&mibextid=ZbWKwL"
                class="btn btn-primary">Facebook</a></li>
            <li><a href="https://www.tiktok.com/@celmexoficial" class="btn btn-primary">TikTok</a></li>
            <li><a href="https://www.instagram.com/celmexoficial/" class="btn btn-primary">Instagram</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Aviso de privacidad</h3>
          <a href="#" class="btn btn-primary">Ver aviso de privacidad</a>
          {% if request.user.is_authenticated %}
          <h6>Hola  {{ user }} </h6>
          <a href="{% url 'sesion:logout' %}" class="btn btn-primary">cerrar sesion</a>
          {% else %}
          <a href="{% url 'sesion:signup' %}" class="btn btn-primary">Le interesa trabajar con CELMEX</a>
       
          <a href="{% url 'sesion:login' %}" class="btn btn-primary">Ya chambeo en CELMEX</a>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h3>Contacto</h3>
          <p>Teléfono: 6647813717</p>
          <p>Correo electrónico: marcacelmex@gmail.com</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

03fplaest-main/templates/core/UsuarioPlanes.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CelMex</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    body {
      background-color: #2f8efa;
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }

    .header {
      background-color: #0d6efd;
    }

    .hero {
      padding: 100px 0;
      text-align: center;
    }

    .hero img {
      max-width: 100%;
      height: auto;
    }

    .telefonos {
      padding: 50px 0;
      text-align: center;
    }

    .product-container {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 20px;
      border: 1px solid #0d6efd;
      border-radius: 10px;
      margin-bottom: 20px;
    }

    .product-container img {
      max-width: 100%;
      height: auto;
      border: 1px solid #0d6efd;
      border-radius: 10px;
    }

    .footer {
      background-color: #0d6efd;
      padding: 50px 0;
      color: white;
    }
  </style>
</head>

<body>

  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">
          <img src="{% static 'images/logo2-removebg-preview(1).png' %}" alt="Tu Sitio Web" width="100px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'core:index' %}">Productos</a>
            <a class="nav-link" href="{% url 'core:accesorios' %}">Accesorios</a>
            <a class="nav-link active" href="{% url 'core:planes' %}">Planes</a>
            <a class="nav-link" href="{% url 'core:recargas' %}">Recargas</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'home:index' %}">admin</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  </header>

  <section class="telefonos">
    <div class="container">
      <h2 class="mb-4">Planes</h2>
      <div class="row">
        {% for plan in planes %}
        <div class="col-md-4">
          <div class="product-container">
            <img src="{{ plan.image.url }}" alt="{{ plan.plan_name }}"
              class="img-fluid rounded shadow-lg border border-primary">
            <h3>{{ plan.plan_name }}</h3>
            <h4 class="product-description">{{ plan.description }}</h4>
            <h5>${{ plan.price }}</h5>
            <a href="https://celmex.ola.click/products" class="btn btn-primary">Ver más</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>Redes sociales</h3>
          <ul class="list-unstyled">
            <li><a href="https://www.facebook.com/profile.php?id=61551257362781&mibextid=ZbWKwL"
                class="btn btn-primary">Facebook</a></li>
            <li><a href="https://www.tiktok.com/@celmexoficial" class="btn btn-primary">TikTok</a></li>
            <li><a href="https://www.instagram.com/celmexoficial/" class="btn btn-primary">Instagram</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Aviso de privacidad</h3>
          <a href="#" class="btn btn-primary">Ver aviso de privacidad</a>
          {% if request.user.is_authenticated %}
          <h6>Hola  {{ user }} </h6>
          <a href="{% url 'sesion:logout' %}" class="btn btn-primary">cerrar sesion</a>
          {% else %}
          <a href="{% url 'sesion:signup' %}" class="btn btn-primary">Le interesa trabajar con CELMEX</a>
       
          <a href="{% url 'sesion:login' %}" class="btn btn-primary">Ya chambeo en CELMEX</a>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h3>Contacto</h3>
          <p>Teléfono: 6647813717</p>
          <p>Correo electrónico: marcacelmex@gmail.com</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

03fplaest-main/templates/core/UsuarioRecargas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CelMex</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    body {
      background-color: #2f8efa;
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }

    .header {
      background-color: #0d6efd;
    }

    .hero {
      padding: 100px 0;
      text-align: center;
    }

    .hero img {
      max-width: 100%;
      height: auto;
    }

    .telefonos {
      padding: 50px 0;
      text-align: center;
    }

    .product-container {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 20px;
      border: 1px solid #0d6efd;
      border-radius: 10px;
      margin-bottom: 20px;
    }

    .product-container img {
      max-width: 100%;
      height: auto;
      border: 1px solid #0d6efd;
      border-radius: 10px;
    }

    .footer {
      background-color: #0d6efd;
      padding: 50px 0;
      color: white;
    }
  </style>
</head>

<body>


  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">
          <img src="{% static 'images/logo2-removebg-preview(1).png' %}" alt="Tu Sitio Web" width="100px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'core:index' %}">Productos</a>
            <a class="nav-link" href="{% url 'core:accesorios' %}">Accesorios</a>
            <a class="nav-link" href="{% url 'core:planes' %}">Planes</a>
            <a class="nav-link active" href="{% url 'core:recargas' %}">Recargas</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'home:index' %}">admin</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <section class="telefonos">
    <div class="container">
      <h2 class="mb-4">Recargas</h2>
      <div class="row">
        {% for re in recargas %}
        <div class="col-md-4">
          <div class="product-container">
            <img src="{{ re.image.url }}" alt="{{ re.recarga_name }}"
              class="img-fluid rounded shadow-lg border border-primary">
            <h3>{{ re.recarga_name }}</h3>
            <h4 class="product-description">{{ re.description }}</h4>
            <h5>${{ re.price }}</h5>
            <a href="https://celmex.ola.click/products" class="btn btn-primary">Ver más</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>Redes sociales</h3>
          <ul class="list-unstyled">
            <li><a href="https://www.facebook.com/profile.php?id=61551257362781&mibextid=ZbWKwL"
                class="btn btn-primary">Facebook</a></li>
            <li><a href="https://www.tiktok.com/@celmexoficial" class="btn btn-primary">TikTok</a></li>
            <li><a href="https://www.instagram.com/celmexoficial/" class="btn btn-primary">Instagram</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Aviso de privacidad</h3>
          <a href="#" class="btn btn-primary">Ver aviso de privacidad</a>
          {% if request.user.is_authenticated %}
          <h6>Hola  {{ user }} </h6>
          <a href="{% url 'sesion:logout' %}" class="btn btn-primary">cerrar sesion</a>
          {% else %}
          <a href="{% url 'sesion:signup' %}" class="btn btn-primary">Le interesa trabajar con CELMEX</a>
       
          <a href="{% url 'sesion:login' %}" class="btn btn-primary">Ya chambeo en CELMEX</a>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h3>Contacto</h3>
          <p>Teléfono: 6647813717</p>
          <p>Correo electrónico: marcacelmex@gmail.com</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

03fplaest-main/templates/core/celmex2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CelMex</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    body {
      background-color: #2f8efa;
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }

    .header {
      background-color: #0d6efd;
    }

    .hero {
      padding: 100px 0;
      text-align: center;
    }

    .hero img {
      max-width: 100%;
      height: auto;
    }

    .telefonos {
      padding: 50px 0;
      text-align: center;
    }

    .product-container {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 20px;
      border: 1px solid #0d6efd;
      border-radius: 10px;
      margin-bottom: 20px;
    }

    .product-container img {
      max-width: 100%;
      height: auto;
      border: 1px solid #0d6efd;
      border-radius: 10px;
    }

    .footer {
      background-color: #0d6efd;
      padding: 50px 0;
      color: white;
    }
  </style>
</head>

<body>

  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">
          <img src="{% static 'images/logo2-removebg-preview(1).png' %}" alt="Tu Sitio Web" width="100px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'core:index' %}">Productos</a>
            <a class="nav-link" href="{% url 'core:accesorios' %}">Accesorios</a>
            <a class="nav-link" href="{% url 'core:planes' %}">Planes</a>
            <a class="nav-link" href="{% url 'core:recargas' %}">Recargas</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'home:index' %}">admin</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <section class="hero">
    <div class="container">
      <img src="{% static 'images/therock.jpeg' %}" alt="Imagen de un teléfono celular con un accesorio CelMex"
        class="img-fluid rounded shadow-lg border border-primary">
      <h1 class="text-center">CelMex: La mejor tienda de telefonía y accesorios en México</h1>
      <p class="text-center">En CelMex, tenemos todo lo que necesitas para tu teléfono celular. Ofrecemos una
        amplia variedad de teléfonos, accesorios, reparaciones y servicios.</p>
      <a href="https://celmex.ola.click/products" class="btn btn-primary">Comprar ahora</a>
    </div>
  </section>

  <section class="telefonos">
    <div class="container">
      <h2 class="mb-4">Teléfonos celulares</h2>
      <div class="row">
        {% for product in products %}
        <div class="col-md-4">
          <div class="product-container">
            <center><img src="{{ product.image.url }}" alt="{{ product.product_name }}"
              class="img-fluid rounded shadow-lg border border-primary"></center>
            <h3>{{ product.product_name }}</h3>
            <h4 class="product-description">{{ product.description }}</h4>
            <h5>${{ product.price }}</h5>
            <a href="https://celmex.ola.click/products" class="btn btn-primary">Ver más</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>Redes sociales</h3>
          <ul class="list-unstyled">
            <li><a href="https://www.facebook.com/profile.php?id=61551257362781&mibextid=ZbWKwL"
                class="btn btn-primary">Facebook</a></li>
            <li><a href="https://www.tiktok.com/@celmexoficial" class="btn btn-primary">TikTok</a></li>
            <li><a href="https://www.instagram.com/celmexoficial/" class="btn btn-primary">Instagram</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Aviso de privacidad</h3>
          <a href="#" class="btn btn-primary">Ver aviso de privacidad</a>
          {% if request.user.is_authenticated %}
          <h6>Hola  {{ user }} </h6>
          <a href="{% url 'sesion:logout' %}" class="btn btn-primary">cerrar sesion</a>
          {% else %}
          <a href="{% url 'sesion:signup' %}" class="btn btn-primary">Le interesa trabajar con CELMEX</a>
       
          <a href="{% url 'sesion:login' %}" class="btn btn-primary">Ya chambeo en CELMEX</a>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h3>Contacto</h3>
          <p>Teléfono: 6647813717</p>
          <p>Correo electrónico: marcacelmex@gmail.com</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>