03fplaest-main/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.shortcuts import render
from core import views

app_name = "core"

urlpatterns = [
        path('', views.Index.as_view(), name="index"),

        path('accesorio/', views.accesorios.as_view(), name="accesorios"),
        path('recargas/', views.recargas.as_view(), name="recargas"),
        path('planes/', views.planes.as_view(), name="planes"),
        path('producto/', views.Producto.as_view(), name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/home/urls.py
from django.urls import path, include
from django.contrib import admin
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    
    path('categoria/', views.Categoria.as_view(), name="categoria"),
    path('nueva/categoria/', views.NewCategory.as_view(), name="newcategory"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
    
    path('accesorio/', views.accesorios.as_view(), name="accesorios"),
    path('new/accesorio/', views.NewAccesorios.as_view(), name="newaccesorios"),
    path('update/accesorio/<int:pk>/', views.UpdateAccesorios.as_view(), name="update_accesorios"),
    path('detail/accesorio/<int:pk>/', views.DetailAccesorios.as_view(), name="detail_accesorios"),
    path('delete/accesorio/<int:pk>/', views.DeleteAccesorios.as_view(), name="delete_accesorios"),
    
    path('recargas/', views.recargas.as_view(), name="recargas"),
    path('new/recargas/', views.NewRecargas.as_view(), name="newrecargas"),
    path('update/recargas/<int:pk>/', views.UpdateRecargas.as_view(), name="update_recargas"),
    path('detail/recargas/<int:pk>/', views.DetailRecargas.as_view(), name="detail_recargas"),
    path('delete/recargas/<int:pk>/', views.DeleteRecargas.as_view(), name="delete_recargas"),
    
    path('planes/', views.planes.as_view(), name="planes"),
    path('new/planes/', views.NewPlanes.as_view(), name="newplanes"),
    path('update/planes/<int:pk>/', views.UpdatePlanes.as_view(), name="update_planes"),
    path('detail/planes/<int:pk>/', views.DetailPlanes.as_view(), name="detail_planes"),
    path('delete/planes/<int:pk>/', views.DeletePlanes.as_view(), name="delete_planes"),
    
    path('producto/', views.Producto.as_view(), name="product"),
    path('nueva/producto/', views.NewProducto.as_view(), name="newproduct"),
    path('update/producto/<int:pk>/', views.UpdateProducto.as_view(), name="update_producto"),
    path('detail/producto/<int:pk>/', views.DetailProducto.as_view(), name="detail_producto"),
    path('delete/producto/<int:pk>/', views.DeleteProducto.as_view(), name="delete_producto"),
    
]

03fplaest-main/sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('administrador/', include("home.urls")),
    path('sesion/', include("sesion.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/home/forms.py
from django import forms

from .models import Product, Accesorios, Planes, Recargas, Category

class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
        "user",
        "name",
        "status"
        ]
        widgets = {
            'user' : forms.Select(attrs={"class": "from-select from-control"}),
            'plan_name' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
        }

class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
        "user",
        "name",
        "status"
        ]
        widgets = {
            'user' : forms.Select(attrs={"class": "from-select from-control"}),
            'plan_name' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
        }

class UpdateAccesoriosForm(forms.ModelForm):
    class Meta:
        model = Accesorios
        fields = [
        "category",
        "accesorios_name",
        'price',
        "description",
        "image",
        "stock",
        "status",
        ]        
        widgets = {
            'category' : forms.Select(attrs={"class": "from-select from-control"}),
            'accesorios_name' : forms.TextInput(attrs={'class': 'from-select from-control','placeholder':'nombre del plan'}),
            'price': forms.NumberInput(attrs={'class': 'from-select from-control','placeholder':'precio del plan'}),
            'description' : forms.TextInput(attrs={'class': 'from-select from-control','placeholder':'nombre del plan'}),
            'stock': forms.NumberInput(attrs={'class': 'from-select from-control','placeholder':'precio del plan'}),
        }


class NewAccesoriosForm(forms.ModelForm):
    class Meta:
        model = Accesorios
        fields = [
        "category",
        "accesorios_name",
        'price',
        "description",
        "stock",
        "image",
        "status",
        ]
        widgets = {
            'category' : forms.Select(attrs={"class": "from-select from-control"}),
            'accesorios_name' : forms.TextInput(attrs={'class': 'from-control','placeholder':'nombre del plan'}),
            'price': forms.NumberInput(attrs={'class': 'from-control','placeholder':'precio del plan'}),
            'description' : forms.TextInput(attrs={'class': 'from-control','placeholder':'nombre del plan'}),
            'stock': forms.NumberInput(attrs={'class': 'from-control','placeholder':'precio del plan'}),
        }



class UpdateRecargasForm(forms.ModelForm):
    class Meta:
        model = Recargas
        fields = [
        "category",
        "recarga_name",
        "price",
        "description",
        "status",
        ]
        widgets = {
            'category' : forms.Select(attrs={"class": "from-select from-control"}),
            'recarga_name' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
            'price': forms.NumberInput(attrs={'placeholder':'precio del plan'}),
            'description' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
        }



class NewRecargasForm(forms.ModelForm):
    class Meta:
        model = Recargas
        fields = [
        "category",
        "recarga_name",
        "price",
        "description",
        "status",
        ]
        widgets = {
            'category' : forms.Select(attrs={"class": "from-select from-control"}),
            'recarga_name' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
            'price': forms.NumberInput(attrs={'placeholder':'precio del plan'}),
            'description' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
        }

class UpdatePlanesForm(forms.ModelForm):
    class Meta:
        model = Planes
        fields = [
        "category",
        "plan_name",
        "price",
        "description",
        "status",
        ]
        widgets = {
            'category' : forms.Select(attrs={"class": "from-select from-control"}),
            'plan_name' : forms.TextInput(attrs={'placeholder':'nombre del plan'}),
            'price': forms.NumberInput(attrs={'placeholder':'precio del plan'}),
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 10,'placeholder':'descripction'})
        }

class NewPlanesForm(forms.ModelForm):
    class Meta:
        model = Planes
        fields = [
        "category",
        "plan_name",
        "price",
        "description",
        "status",
        ]
        widgets = {
            'category': forms.Select(attrs={"class":"from-select from-control"}),
            'plan_name': forms.TextInput(attrs={'placeholder':'Nombre del plan',}),
            'price': forms.NumberInput(attrs={'placeholder':'Precio del plan','step':'0.1'}),
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 25,'style':'resize: none'})
            

        }


class UpdateProducsForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
        "category",
        "product_name",
        "price",
        "description",
        "image",
        "stock",
        "status",
        ]
        widgets = {
            "category": forms.Select(attrs={"class":"form-select form-control"}),
            "product_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "stock": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
   
        }


class NewProducsForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
        "category",
        "product_name",
        "price",
        "description",
        "image",
        "stock",
        "status",
        ]
        widgets = {
            "category": forms.Select(attrs={"class":"form-select form-control"}),
            "product_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "stock": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
   
        }

03fplaest-main/home/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.conf import settings
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request):
        self.context = {
            "products": Product.objects.all()
        }
        return render(request, self.template_name, self.context)
    

#
#PRODUCT 
#

class Producto(LoginRequiredMixin, generic.View):
    template_name = "home/product/product.html"
    context = {}
    login_url = reverse_lazy("sesion:login")
    def get(self, request):
        #Armasgay es la variable donde se guarda la consulta de base de datos
        self.context = {
            "Armasgay": Product.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class DetailProducto(LoginRequiredMixin, generic.DetailView):
    template_name = "home/product/detail_product.html"
    model = Product
    login_url = reverse_lazy("sesion:login")

class UpdateProducto(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/product/update_planes.html"
    model = Product
    form_class = UpdateProducsForm
    success_url = reverse_lazy("home:product")
    login_url = reverse_lazy("sesion:login")

class DeleteProducto(LoginRequiredMixin, generic.DeleteView):
    template_name = "home/product/delete_product.html"
    model = Product
    success_url = reverse_lazy("home:product")
    login_url = reverse_lazy("sesion:login")

class NewProducto(LoginRequiredMixin, generic.CreateView):
    template_name = "home/product/newproduct.html"
    model = Product
    form_class = NewProducsForm
    success_url = reverse_lazy("home:product")
    login_url = reverse_lazy("sesion:login")


#
#CATEGORIA 
#
class Categoria(LoginRequiredMixin, generic.View):
    template_name = "home/category.html"
    context = {}
    login_url = reverse_lazy("sesion:login")
    def get(self, request):
        self.context = {
            "category": Category.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class DetailCategory(LoginRequiredMixin, generic.DetailView):
    template_name = "home/detail_category.html"
    model = Category
    login_url = reverse_lazy("sesion:login")

class UpdateCategory(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_category.html"
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy("home:categoria")
    login_url = reverse_lazy("sesion:login")

class DeleteCategory(LoginRequiredMixin, generic.DeleteView):
    template_name = "home/delete_category.html"
    model = Category
    success_url = reverse_lazy("home:categoria")
    login_url = reverse_lazy("sesion:login")


class NewCategory(LoginRequiredMixin, generic.CreateView):
    template_name = "home/newcategory.html"
    model = Category
    form_class = NewCategoryForm
    success_url = reverse_lazy("home:categoria")
    login_url = reverse_lazy("sesion:login")


#
#ACCESORIOS
#
class accesorios(LoginRequiredMixin, generic.View):
    template_name = "home/accesorios.html"
    context = {}
    login_url = reverse_lazy("sesion:login")

    def get(self, request):
        self.context = {
            "accesorios": Accesorios.objects.all()
        }
        return render(request, self.template_name, self.context)

class DetailAccesorios(LoginRequiredMixin, generic.DetailView):
    template_name = "home/detail_accesorios.html"
    model = Accesorios
    login_url = reverse_lazy("sesion:login")


class UpdateAccesorios(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_accesorios.html"
    model = Accesorios
    form_class = UpdateAccesoriosForm
    success_url = reverse_lazy("home:accesorios")
    login_url = reverse_lazy("sesion:login")


class DeleteAccesorios(LoginRequiredMixin, generic.DeleteView):
    template_name = "home/delete_accesorios.html"
    model = Accesorios
    success_url = reverse_lazy("home:accesorios")
    login_url = reverse_lazy("sesion:login")


class NewAccesorios(LoginRequiredMixin, generic.CreateView):
    template_name = "home/newaccesorios.html"
    model = Accesorios
    form_class = NewAccesoriosForm
    success_url = reverse_lazy("home:accesorios")
    login_url = reverse_lazy("sesion:login")



#
#RECARGASD
#
class recargas(LoginRequiredMixin, generic.View):
    template_name = "home/recargas.html"
    context = {}
    login_url = reverse_lazy("sesion:login")

    def get(self, request):
        self.context = {
            "recargas": Recargas.objects.all()
        }
        return render(request, self.template_name, self.context)

class DetailRecargas(LoginRequiredMixin, generic.DetailView):
    template_name = "home/detail_recargas.html"
    model = Recargas
    login_url = reverse_lazy("sesion:login")

    def get(self, request, pk, *args, **kwargs):
        product = Recargas.objects.get(pk=pk)
        self.context = {
            "object": product
        }
        return render(request, self.template_name,self.context)

class UpdateRecargas(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_recargas.html"
    model = Recargas
    form_class = UpdateRecargasForm
    success_url = reverse_lazy("home:recargas")
    login_url = reverse_lazy("sesion:login")


class DeleteRecargas(LoginRequiredMixin, generic.DeleteView):
    template_name = "home/delete_recargas.html"
    model = Recargas
    success_url = reverse_lazy("home:recargas")
    login_url = reverse_lazy("sesion:login")


class NewRecargas(LoginRequiredMixin, generic.CreateView):
    template_name = "home/newrecargas.html"
    model = Recargas
    form_class = NewRecargasForm
    success_url = reverse_lazy("home:recargas")
    login_url = reverse_lazy("sesion:login")









#
#PLANES
#
class planes(LoginRequiredMixin, generic.View):
    template_name = "home/planes.html"
    context = {}
    login_url = reverse_lazy("sesion:login")

    def get(self, request):
        self.context = {
            "planes": Planes.objects.all()
        }
        return render(request, self.template_name, self.context)

class DetailPlanes(LoginRequiredMixin, generic.DetailView):
    template_name = "home/detail_planes.html"
    model = Planes
    login_url = reverse_lazy("sesion:login")

    def get(self, request, pk, *args, **kwargs):
        product = Planes.objects.get(pk=pk)
        self.context = {
            "object": product
        }
        return render(request, self.template_name,self.context)

class UpdatePlanes(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_planes.html"
    model = Planes
    form_class = UpdatePlanesForm
    success_url = reverse_lazy("home:planes")
    login_url = reverse_lazy("sesion:login")


class DeletePlanes(LoginRequiredMixin, generic.DeleteView):
    template_name = "home/delete_plan.html"
    model = Planes
    success_url = reverse_lazy("home:planes")
    login_url = reverse_lazy("sesion:login")


class NewPlanes(LoginRequiredMixin, generic.CreateView):
    template_name = "home/newplanes.html"
    model = Planes
    form_class = NewPlanesForm
    success_url = reverse_lazy("home:planes")
    login_url = reverse_lazy("sesion:login")

03fplaest-main/templates/home/accesorios.html
{% extends 'base/base.html' %}

{% block title %}Accesorios View{% endblock title %}

{% block content %} 


<div class="container">
    <table class="table table-striped">
        <thead>
            <th class="text-center">ID</th>
            <th class="text-center">Name</th>
            <th class="text-center">Price</th>
            <th class="text-center">Description</th>
            <th class="text-center">Image</th>
            <th class="text-center">Stock</th>
            <th class="text-center">Status</th>
            <th class="text-center">Category</th>
            <th class="text-center">Actions</th>
        </thead>
        <tbody>
            {% for acc in accesorios %}
                <tr>
                    <td class="text-center">{{ acc.id }}</td>
                    <td class="text-center">{{ acc.accesorios_name }}</td>
                    <td class="text-center">{{ acc.price }}</td>
                    <td class="text-center">{{ acc.description }}</td>
                    <td class="text-center">
                        <img src="{{ acc.image.url }}" alt="{{ acc.accesorios_name }}" class="img-fluid" style="max-width: 100px;">
                    </td>
                    <td class="text-center">{{ acc.stock }}</td>
                    <td class="text-center">{{ acc.status }}</td>
                    <td class="text-center">{{ acc.category }}</td>
                    <td class="text-center">
                        <a href="{% url 'home:detail_accesorios' acc.id %}" class="btn btn-primary btn-sm">Detail</a>
                        <a href="{% url 'home:update_accesorios' acc.id %}" class="btn btn-warning btn-sm">Update</a>
                        <a href="{% url 'home:delete_accesorios' acc.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

03fplaest-main/templates/home/delete_accesorios.html
{% extends 'base/base.html' %}

{% block title %}Delete Accesorios View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            ¿ Realmente deseas eliminar este accesorio: <strong>{{object}}??</strong>
            <a href="{% url 'home:accesorios' %}" class="btn btn-outline-info">Cancel</a>
            <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

03fplaest-main/templates/home/detail_accesorios.html
{% extends 'base/base.html' %}

{% block title %}Detail Accesorios View{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{ object }}
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <p class="lead">{{ object.description }}</p>
                    <small><a href="{% url 'home:accesorios' %}" class="btn btn-link">Back to Home</a></small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

03fplaest-main/templates/home/detail_category.html
{% extends 'base/base.html' %}

{% block title %}Detail Category View{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{ object }}
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <p class="lead">{{ object.description }}</p>
                    <small><a href="{% url 'home:index' %}" class="btn btn-link">Back to Home</a></small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

03fplaest-main/templates/home/detail_planes.html
{% extends 'base/base.html' %}

{% block title %}Detail Plan View{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{ object }}
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <p class="lead">{{ object.description }}</p>
                    <small><a href="{% url 'home:planes' %}" class="btn btn-link">Back to Home</a></small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

03fplaest-main/templates/home/detail_recargas.html
{% extends 'base/base.html' %}

{% block title %}Detail Accesorios View{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{ object }}
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <p class="lead">{{ object.description }}</p>
                    <small><a href="{% url 'home:recargas' %}" class="btn btn-link">Back to Home</a></small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

03fplaest-main/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Index View{% endblock title %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<div class="container">
    <table class="table table-striped">
        <thead>
            <th class="text-center">ID</th>
            <th class="text-center">Product Name</th>
            <th class="text-center">Price</th>
            <th class="text-center">Description</th>
            <th class="text-center">Image</th>
            <th class="text-center">Stock</th>
            <th class="text-center">Status</th>
            <th class="text-center">Category</th>
            <th class="text-center">Actions</th>
        </thead>
{% for product in products %}
                <tr>
                    <td class="text-center">{{ product.id }}</td>
                    <td class="text-center">{{ product.product_name }}</td>
                    <td class="text-center">{{ product.price }}</td>
                    <td class="text-center">{{ product.description }}</td>
                    <td class="text-center">
                        <img src="{{ product.image.url }}" alt="{{ product.product_name }}" class="img-fluid" style="max-width: 100px;">
                    </td>
                    <td class="text-center">{{ product.stock }}</td>
                    <td class="text-center">{{ product.status }}</td>
                    <td class="text-center">{{ product.category }}</td>
                    <td class="text-center">
                        <a href="{% url 'home:detail_category' product.id %}" class="btn btn-primary btn-sm">Detail</a>
                        <a href="{% url 'home:update_category' product.id %}" class="btn btn-warning btn-sm">Update</a>
                        <a href="{% url 'home:delete_category' product.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

03fplaest-main/templates/home/newcategory.html
{% extends 'base/base.html' %}

{% block title %}New Category View{% endblock title %}

{% block content %}
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title mb-4 text-center">Nueva Categoria</h2>
            <form action="" method="post" class="form" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              
              <div class="d-flex justify-content-between mt-4">
                <a href="{% url 'home:categoria' %}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-success">Guardar Categoria</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

03fplaest-main/templates/home/planes.html
{% extends 'base/base.html' %}

{% block title %}Planes View{% endblock title %}

{% block content %}


<div class="container">
    <table class="table table-striped">
        <thead>
            <th class="text-center">ID</th>
            <th class="text-center">recarga Name</th>
            <th class="text-center">Price</th>
            <th class="text-center">Description</th>
            <th class="text-center">Status</th>
            <th class="text-center">Category</th>
            <th class="text-center">Actions</th>
        </thead>
        <tbody>
            {% for plan in planes %}
                <tr>
                    <td class="text-center">{{ plan.id }}</td>
                    <td class="text-center">{{ plan.plan_name }}</td>
                    <td class="text-center">{{ plan.price }}</td>
                    <td class="text-center">{{ plan.description }}</td>
                    <td class="text-center">{{ plan.status }}</td>
                    <td class="text-center">{{ plan.category }}</td>
                    <td class="text-center">
                        <a href="{% url 'home:detail_planes' plan.id %}" class="btn btn-primary btn-sm">Detail</a>
                        <a href="{% url 'home:update_planes' plan.id %}" class="btn btn-warning btn-sm">Update</a>
                        <a href="{% url 'home:delete_planes' plan.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

03fplaest-main/templates/home/recargas.html
{% extends 'base/base.html' %}

{% block title %}Accesorios View{% endblock title %}

{% block content %}


<div class="container">
    <table class="table table-striped">
        <thead>
            <th class="text-center">ID</th>
            <th class="text-center">recarga Name</th>
            <th class="text-center">Price</th>
            <th class="text-center">Description</th>
            <th class="text-center">Status</th>
            <th class="text-center">Category</th>
        </thead>
        <tbody>
            {% for re in recargas %}
                <tr>
                    <td class="text-center">{{ re.id }}</td>
                    <td class="text-center">{{ re.recarga_name }}</td>
                    <td class="text-center">{{ re.price }}</td>
                    <td class="text-center">{{ re.description }}</td>
                    <td class="text-center">{{ re.status }}</td>
                    <td class="text-center">{{ re.category }}</td>
                    <td class="text-center">
                        <a href="{% url 'home:detail_recargas' re.id %}" class="btn btn-primary btn-sm">Detail</a>
                        <a href="{% url 'home:update_recargas' re.id %}" class="btn btn-warning btn-sm">Update</a>
                        <a href="{% url 'home:delete_recargas' re.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

03fplaest-main/templates/home/update_category.html
{% extends 'base/base.html' %}

{% block title %}Update Category View{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">Update Category</div>

                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="mt-4">
                            <a href="{% url 'home:index'%}" class="btn btn-outline-info">Cancel</a>
                            <button type="submit" class="btn btn-warning">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}