03fplaest-main/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.shortcuts import render
from core import views

app_name = "core"

urlpatterns = [
        path('', views.Index.as_view(), name="index"),

        path('accesorio/', views.accesorios.as_view(), name="accesorios"),
        path('recargas/', views.recargas.as_view(), name="recargas"),
        path('planes/', views.planes.as_view(), name="planes"),
        path('producto/', views.Producto.as_view(), name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/home/urls.py
from django.urls import path, include
from django.contrib import admin
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    
    path('categoria/', views.Categoria.as_view(), name="categoria"),
    path('nueva/categoria/', views.NewCategory.as_view(), name="newcategory"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
    
    path('accesorio/', views.accesorios.as_view(), name="accesorios"),
    path('new/accesorio/', views.NewAccesorios.as_view(), name="newaccesorios"),
    path('update/accesorio/<int:pk>/', views.UpdateAccesorios.as_view(), name="update_accesorios"),
    path('detail/accesorio/<int:pk>/', views.DetailAccesorios.as_view(), name="detail_accesorios"),
    path('delete/accesorio/<int:pk>/', views.DeleteAccesorios.as_view(), name="delete_accesorios"),
    
    path('recargas/', views.recargas.as_view(), name="recargas"),
    path('new/recargas/', views.NewRecargas.as_view(), name="newrecargas"),
    path('update/recargas/<int:pk>/', views.UpdateRecargas.as_view(), name="update_recargas"),
    path('detail/recargas/<int:pk>/', views.DetailRecargas.as_view(), name="detail_recargas"),
    path('delete/recargas/<int:pk>/', views.DeleteRecargas.as_view(), name="delete_recargas"),
    
    path('planes/', views.planes.as_view(), name="planes"),
    path('new/planes/', views.NewPlanes.as_view(), name="newplanes"),
    path('update/planes/<int:pk>/', views.UpdatePlanes.as_view(), name="update_planes"),
    path('detail/planes/<int:pk>/', views.DetailPlanes.as_view(), name="detail_planes"),
    path('delete/planes/<int:pk>/', views.DeletePlanes.as_view(), name="delete_planes"),
    
    path('producto/', views.Producto.as_view(), name="product"),
    path('nueva/producto/', views.NewProducto.as_view(), name="newproduct"),
    path('update/producto/<int:pk>/', views.UpdateProducto.as_view(), name="update_producto"),
    path('detail/producto/<int:pk>/', views.DetailProducto.as_view(), name="detail_producto"),
    path('delete/producto/<int:pk>/', views.DeleteProducto.as_view(), name="delete_producto"),
    
]

03fplaest-main/sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('administrador/', include("home.urls")),
    path('sesion/', include("sesion.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03fplaest-main/templates/base/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CelMex{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">

      
    <style>
        body {
            background-color: #f8f9fa;
     
        }

        .container {
            margin-top: 20px;
        }

        .navbar {
            background-color: #007bff;
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            color: #fff !important;
        }

        .navbar-toggler-icon {
            background-color: #fff;
        }

        .dropdown-menu {
            background-color: #007bff;
        }

        .dropdown-item {
            color: #fff !important;
        }

        .dropdown-item:hover {
            background-color: #0056b3;
        }

        .form-control {
            background-color: #f2f2f2;
        }

        .btn-outline-success {
            color: #28a745;
            border-color: #28a745;
        }

        .btn-outline-success:hover {
            background-color: #28a745;
            color: #fff;
        }
    </style>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'core:index' %}">CelMex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="equiposDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Equipos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="equiposDropdown">
                                <li><a class="dropdown-item" href="{% url 'home:product' %}">Ver Equipos</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:newproduct' %}">Agregar Equipo</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'home:accesorios' %}" id="accesoriosDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Accesorios
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="accesoriosDropdown">
                                <li><a class="dropdown-item" href="{% url 'home:accesorios' %}">Ver Accesorios</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:newaccesorios' %}">Agregar Accesorios al
                                        sistema</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Recargas
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'home:recargas' %}">recargas disponibles</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'home:newrecargas' %}">Crear nuevas recargas</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Planes
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'home:planes' %}">Planes disponibles</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:newplanes' %}">Agregar nuevo plan</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Categoria
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'home:categoria' %}">Categorias</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:newcategory' %}">Agregar una nueva
                                        categoria</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock content %}
</body>
</html>